[project]
name = "iotdevice"
version = "0.9.0"
description = ""
authors = [
    {name = "Jonathan Bydendyk",email = "jonathan@hacklab.co.za"}
]
license = {text = "BSD-3-Clause"}
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bitstring (>=4.3.1,<5.0.0)",
    "click (>=8.3.1,<9.0.0)",
    "esptool (>=5.1.0,<6.0.0)",
    "pycparser (>=2.23,<3.0)",
    "pyserial (>=3.5,<4.0)",
    "python-dotenv (>=1.2.1,<2.0.0)",
    "mpremote (>=1.29.0,<2.0.0)",
]

[dependency-groups]
dev = [
    'pytest>=9.0.1,<10.0.0',
    'pytest-cov>=7.0.0,<8.0.0',
    'ruff>=0.16.9,<0.17.0',
    "pre-commit (>=4.6.2,<5.0.0)",
]

[tool.poetry]
requires-poetry = '>=2.2.1,<3.0.0'

[tool.ruff]
target-version = "py313"
line-length = 80

[tool.ruff.lint]
select = ["E", "F", "W", "C90", "B", "I"]
ignore = ["E203"]

[tool.ruff.lint.pycodestyle]
max-line-length = 88

[tool.ruff.lint.mccabe]
max-complexity = 18

[tool.ruff.lint.isort]
known-first-party = ["iotdevice"]

[tool.ruff.format]
quote-style = "preserve"

[tool.coverage.run]
branch = true
relative_files = true
source = ["iotdevice"]
omit = [
    "*/config/*",
    "*/drivers/*",
    "*/tests/*",
    "*/__init__.py",
    "iotdevice/boot.py",
    "cli.py",
]

[tool.pytest.ini_options]
testpaths = ["iotdevice/tests"]
addopts = "--cov=iotdevice --cov-branch"

[tool.coverage.report]
show_missing = true
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "raise AssertionError",
    "raise NotImplementedError",
    "if __name__ == .__main__.:",
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
